source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'sinatra', require: false
gem 'slim'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'chronic'

gem 'omniauth-facebook'

# gem "mail"

gem 'sidekiq', '>= 2.12.1'
gem 'sidekiq-status'
gem 'sidekiq-failures'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem "twitter-bootstrap-rails"

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end
# gem 'cocoon'
gem 'jquery-rails'

group :development, :test do
  gem 'rspec-rails'
  gem 'sextant'
  gem 'better_errors'
  gem 'faker'
  gem 'factory_girl_rails'
  gem 'shoulda'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'pry-rails'
  gem 'database_cleaner'
  gem 'quiet_assets'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
gem 'debugger'
